default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: message_me_development
  username: root
  password:
  host: localhost

test:
  <<: *default
  database: message_me_test
  username: root
  password:
  host: localhost

production:
  <<: *default
  database: message_me_production
  username: your_mysql_username
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: your_production_database_host
  # Uncomment the line below to enable SSL in production
  # sslca: /path/to/ca-cert.pem
  # sslkey: /path/to/client-key.pem
  # sslcert: /path/to/client-cert.pem

